version: '3'

services:
  app:
    build:
      context: ./app
    container_name: app
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  db:
    build:
      context: ./db
    container_name: db
    restart: always
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_USER: user
      MYSQL_PASSWORD: senha
      MYSQL_DATABASE: node
    ports:
      - "3306:3306"
    # volumes:
    #   - ./db/data:/var/lib/mysql
    depends_on:
      - app
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network



networks:
  app-network:
    driver: bridge
